services:
  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      app1:
        condition: service_started
      app2:
        condition: service_started
      app3:
        condition: service_started
      app4:
        condition: service_started
      app5:
        condition: service_started

  app1:
    build: ./app1

  app2:
    build: ./app2

  app3:
    build: ./app3

  app4:
    build: ./app4

  app5:
    build: ./app5
